services:

  server:
    build: .
    restart: always
    container_name: server
    network_mode: service:tor
    volumes:
      - ./docker/config.yml:/btry.yml
      - ./docker/volumes/lnd:/home/lnd/.lnd
    depends_on:
      - tor
      - bitcoind
      - lnd
  
  bitcoind:
    build: ./docker/bitcoind
    restart: always
    stop_grace_period: 30s
    container_name: bitcoind
    network_mode: service:tor
    volumes:
      - ./docker/volumes/bitcoind:/home/bitcoin/.bitcoin
      - ./docker/volumes/tor/data:/var/lib/tor:ro
      - ./docker/volumes/tor/config:/etc/tor:ro
    depends_on:
      - tor

  lnd:
    build: ./docker/lnd
    restart: always
    stop_grace_period: 30s
    container_name: lnd
    command: lnd
    network_mode: service:tor
    environment:
      AUTO_UNLOCK_PASSWORD: ${AUTO_UNLOCK_PASSWORD}
    volumes:
      - ./docker/volumes/lnd:/home/lnd/.lnd
      - ./docker/volumes/tor/data:/var/lib/tor:ro
      - ./docker/volumes/tor/config:/etc/tor:ro
    depends_on:
      - tor
      - bitcoind

  tor:
    build: ./docker/tor
    restart: always
    stop_grace_period: 30s
    container_name: tor
    volumes:
      - ./docker/volumes/tor/data:/var/lib/tor
      - ./docker/volumes/tor/config:/etc/tor
    ports:
      - 21000:21000 # BTRY server
