name: Test

on:
  push:
    branches:
      - "master"
  pull_request:
    paths-ignore:
      - "docker/**"

jobs:
  server:
    name: Tests (Server)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          check-latest: true
          cache: true

      - name: Run tests
        # Create an empty file inside dist so Go does not fail when compiling the code
        run: mkdir ./ui/dist && touch ./ui/dist/tmp && go test ./...
  
    ui:
      name: Tests (UI)
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: 20
            cache: npm
            cache-dependency-path: ui/package-lock.json

        - name: Run tests
          run: |
            npm ci
            npm run test
          working-directory: ui
