name: Unit tests (UI)

on:
  push:
    branches:
      - "master"
  pull_request:
    paths:
      - '.github/workflows/ui-unit-tests.yml'
      - "ui/**"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Run tests
        working-directory: ui
        run: |
          npm ci
          npm run test
